# Do not change the next 2 values
COOPERATE = 0
DEFECT = 1

# Classical Prisoner's Dilemma
DEFECT_DEFECT = (-2, -2)
COOPERATE_DEFECT = (-3, 0)
DEFECT_COOPERATE = (0, -3)
COOPERATE_COOPERATE = (-1, -1)

# Friend or Foe Game
# DEFECT_DEFECT = (0, 0)
# COOPERATE_DEFECT = (0, 2)
# DEFECT_COOPERATE = (2, 0)
# COOPERATE_COOPERATE = (1, 1)

MEMORY_SIZE = 10

S = -5.0
RECONNECT_PROB = 0.05

TRACK_INDIVIDUAL = True
COPY_MEMORY = True
